<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <OutputPath>$(SolutionDir)..\bin\$(Configuration)\plugins</OutputPath>
    <AssemblyTitle>JsonColumnizer</AssemblyTitle>
    <RootNamespace>JsonColumnizer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColumnizerLib\ColumnizerLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <None Update="JsonColumnizer.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
